# Generated by Django 6.0.5 on 2026-07-24 23:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_seed_payment_modes'),
        ('settings', '0005_alter_restaurant_options_alter_room_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSClosingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start_date', models.DateTimeField(editable=False)),
                ('period_end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('posting_date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('total_taxes', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('total_short_excess', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_closing_entries', to='settings.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_closing_entries', to=settings.AUTH_USER_MODEL)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_closing_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end_date'],
            },
        ),
        migrations.CreateModel(
            name='POSOpeningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('period_end_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('posting_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_opening_entries', to='settings.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_opening_entries', to=settings.AUTH_USER_MODEL)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_opening_entries', to=settings.AUTH_USER_MODEL)),
                ('closing_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_entry_ref', to='staff.posclosingentry')),
            ],
            options={
                'ordering': ['-period_start_date'],
            },
        ),
        migrations.AddField(
            model_name='posclosingentry',
            name='opening_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closing_entry_for', to='staff.posopeningentry'),
        ),
        migrations.CreateModel(
            name='ClosingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('closing_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closing_payments', to='payments.modeofpayment')),
                ('closing_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_payments', to='staff.posclosingentry')),
            ],
            options={
                'ordering': ['mode_of_payment__name'],
                'unique_together': {('closing_entry', 'mode_of_payment')},
            },
        ),
        migrations.CreateModel(
            name='OpeningPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_payments', to='payments.modeofpayment')),
                ('opening_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_payments', to='staff.posopeningentry')),
            ],
            options={
                'ordering': ['mode_of_payment__name'],
                'unique_together': {('opening_entry', 'mode_of_payment')},
            },
        ),
    ]
