# Generated by Django 6.0.5 on 2026-07-27 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_phase6_pos_profile_production_unit_tax'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posopeningentry',
            name='pos_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_entries', to='settings.posprofile'),
        ),
    ]
