# Generated by Django 6.0.5 on 2026-07-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_posopeningentry_pos_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posclosingentry',
            name='total_taxes',
        ),
    ]
