# Generated by Django 6.0.5 on 2026-07-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_posclosingentry_total_taxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posclosingentry',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='posopeningentry',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='posopeningentry',
            name='pos_profile',
        ),
    ]
