# Generated by Django 6.0.5 on 2026-08-02 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_posclosingentry_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='posopeningentry',
            index=models.Index(fields=['status', 'period_start_date'], name='staff_posop_status_2ab096_idx'),
        ),
    ]
