# Generated by Django 6.0.5 on 2026-08-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('staff', '0005_posopeningentry_staff_posop_status_2ab096_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='posclosingentry',
            name='variance_journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_variance_closing', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='posclosingentry',
            name='variance_note',
            field=models.TextField(blank=True, help_text='Required when the absolute variance exceeds the configured approval threshold.'),
        ),
    ]
