# Generated by Django 6.0.5 on 2026-09-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_posclosingentry_variance_journal_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posclosingentry',
            name='variance_note',
            field=models.TextField(blank=True, help_text='Required when the cash difference is large enough to need manager approval.'),
        ),
    ]
