# Generated by Django 6.0.5 on 2026-09-11 07:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_posclosingentry_variance_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='posclosingentry',
            name='bill_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='posclosingentry',
            name='refunded_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
    ]
