# Generated by Django 6.0.5 on 2026-09-16 06:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_shiftcashout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingpayment',
            name='closing_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
