# Generated by Django 6.0.5 on 2026-07-28 14:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0020_remove_reconciliation_item_warehouse'),
        ('menu', '0004_alter_menu_options'),
        ('payments', '0002_seed_payment_modes'),
        ('settings', '0008_single_pos_profile_per_restaurant'),
        ('staff', '0002_posopeningentry_pos_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('New Order', 'New Order'), ('Order Modified', 'Order Modified'), ('Cancelled', 'Cancelled'), ('Partially Cancelled', 'Partially Cancelled')], max_length=25)),
                ('naming_series', models.CharField(max_length=50)),
                ('kot_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=15)),
                ('posting_datetime', models.DateTimeField(auto_now_add=True)),
                ('original_kots', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.branch')),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kots', to='settings.productionunit')),
            ],
            options={
                'ordering': ['-posting_datetime'],
            },
        ),
        migrations.CreateModel(
            name='KOTItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('customer_index', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('kot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.kot')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKE_AWAY', 'Take Away'), ('DELIVERY', 'Delivery'), ('PHONE_IN', 'Phone In')], default='DINE_IN', max_length=20)),
                ('customer_name', models.CharField(default='Walk-in Customer', max_length=200)),
                ('customer_mobile', models.CharField(blank=True, max_length=20)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('invoice_printed', models.BooleanField(default=False)),
                ('posting_date', models.DateField(default=django.utils.timezone.now)),
                ('posting_time', models.TimeField(default=django.utils.timezone.now)),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('total_taxes', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('rounded_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('comments', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('order_number', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='settings.branch')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_orders', to=settings.AUTH_USER_MODEL)),
                ('opening_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='staff.posopeningentry')),
                ('pos_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.posprofile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='settings.restaurant')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.room')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='settings.table')),
                ('taxes_and_charges_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.taxtemplate')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posting_date', '-posting_time'],
            },
        ),
        migrations.AddField(
            model_name='kot',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kots', to='orders.order'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('customer_index', models.PositiveIntegerField(default=1)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(choices=[('FOOD', 'Food'), ('DRINKS', 'Drinks')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.item')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.pricelist')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.uom')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.modeofpayment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('charge_type', models.CharField(max_length=30)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_head', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='orders.order')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['posting_date'], name='orders_orde_posting_0251ed_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch'], name='orders_orde_branch__c40543_idx'),
        ),
    ]
