# Generated by Django 6.0.5 on 2026-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='synced',
            field=models.BooleanField(default=False, editable=False)),
    ]
