# Generated by Django 6.0.5 on 2026-07-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_orderitem_synced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='waiter'),
    ]
