# Generated by Django 6.0.5 on 2026-07-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_waiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount'),
    ]
