# Generated by Django 6.0.5 on 2026-07-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='room'),
        migrations.RemoveField(
            model_name='order',
            name='table'),
    ]
