# Generated by Django 6.0.5 on 2026-07-30 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_room_remove_order_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kot",
            name="naming_series",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price_list",
        ),
        migrations.AddField(
            model_name="kot",
            name="order_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="arrived_time",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_spend_time",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="invoice_number",
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="posting_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="order",
            name="posting_time",
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="orders.order",
            ),
        ),
    ]
