# Generated by Django 6.0.5 on 2026-07-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_kot_naming_series_remove_orderitem_price_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='taxes_and_charges_template',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_taxes',
        ),
        migrations.DeleteModel(
            name='OrderTax',
        ),
    ]
