# Generated by Django 6.0.5 on 2026-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_taxes_and_charges_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKE_AWAY', 'Take Away')], default='DINE_IN', max_length=20),
        ),
    ]
