# Generated by Django 6.0.5 on 2026-07-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_branch__c40543_idx',
        ),
        migrations.RemoveField(
            model_name='kot',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pos_profile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
    ]
