# Generated by Django 6.0.5 on 2026-07-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_orders_orde_branch__c40543_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amended_from',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='outstanding_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_spend_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='department',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='uom',
        ),
    ]
