# Generated by Django 6.0.5 on 2026-07-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_amended_from_remove_order_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_return',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='return_against',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to='orders.order'),
        ),
    ]
