# Generated by Django 6.0.5 on 2026-08-02 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_seed_order_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kot',
            name='print_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRINTED', 'Printed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='kot',
            name='ticket_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bar', 'Bar')], default='kitchen', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
