# Generated by Django 6.0.5 on 2026-08-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_backfill_kot_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('wrong_order', 'Wrong order'), ('customer_changed_mind', 'Customer changed mind'), ('cashier_error', 'Cashier error'), ('other', 'Other')], max_length=50),
        ),
    ]
