# Generated by Django 6.0.5 on 2026-08-02 09:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_warehouse_unique_together_alter_warehouse_name_and_more'),
        ('menu', '0007_menuitem_menu_item_rate_gte_zero'),
        ('orders', '0016_alter_order_cancel_reason'),
        ('payments', '0004_modeofpayment_payments_one_default_mode'),
        ('staff', '0004_remove_posclosingentry_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='synced',
        ),
        migrations.AddField(
            model_name='kot',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kot',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_kots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_printed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_printed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='rounding_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_warehouse',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_stock_snapshots', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='order',
            name='submitted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='department',
            field=models.CharField(blank=True, choices=[('FOOD', 'Food'), ('DRINKS', 'Drinks')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_against_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='kot',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kots', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='kot',
            name='type',
            field=models.CharField(choices=[('New Order', 'New Order'), ('Cancelled', 'Cancelled')], max_length=25),
        ),
        migrations.AlterField(
            model_name='kotitem',
            name='kot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.kot'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'updated_at'], name='orders_orde_status_728b00_idx'),
        ),
        migrations.AddConstraint(
            model_name='kotitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='orders_kot_item_qty_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='kotitem',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_qty__gte', 0)), name='orders_kot_cancelled_qty_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='kotitem',
            constraint=models.CheckConstraint(condition=models.Q(('customer_index__gte', 1)), name='orders_kot_customer_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('guest_count__gte', 1)), name='orders_guest_count_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancel_reason', ''), _negated=True), _connector='OR'), name='orders_cancelled_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('order_number__isnull', False)), fields=('order_number',), name='orders_order_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0), ('return_against_item__isnull', False), _connector='OR'), name='orders_item_qty_valid'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='orders_item_rate_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('customer_index__gte', 1)), name='orders_item_customer_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='orderpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='orders_payment_amount_gt_zero'),
        ),
        migrations.AddField(
            model_name='orderauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderauditevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='orders.order'),
        ),
    ]
