# Generated by Django 6.0.5 on 2026-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_backfill_orderitem_department'),
        ('payments', '0004_modeofpayment_payments_one_default_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_item',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='orderpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_no', ''), _negated=True), fields=('mode_of_payment', 'reference_no'), name='orders_payment_reference_unique'),
        ),
    ]
