# Generated by Django 6.0.5 on 2026-08-02 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_backfill_orderitem_stock_item'),
        ('settings', '0023_restaurant_singleton_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kot',
            index=models.Index(fields=['status', 'print_status', '-posting_datetime'], name='orders_kot_status_4fb02b_idx'),
        ),
    ]
