# Generated by Django 6.0.5 on 2026-08-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_discarded_at_order_discarded_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderpayment',
            name='orders_payment_amount_gt_zero',
        ),
    ]
