# Generated by Django 6.0.5 on 2026-08-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_orderpayment_orders_payment_amount_gt_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='not_restockable',
            field=models.BooleanField(default=False, help_text='Return lines only: when set, the returned stock is not restored (wastage).'),
        ),
    ]
