# Generated by Django 6.0.5 on 2026-08-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_itemgroup_expense_account_itemgroup_income_account_and_more'),
        ('menu', '0007_menuitem_menu_item_rate_gte_zero'),
        ('orders', '0025_orderitem_not_restockable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('not_restockable', True), _negated=True), ('return_against_item__isnull', False), _connector='OR'), name='orders_item_not_restockable_return_only'),
        ),
    ]
