# Generated by Django 6.0.5 on 2026-09-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_orderitem_orders_item_not_restockable_return_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='not_restockable',
            field=models.BooleanField(default=False, help_text='For returns only: when set, the returned items are treated as wastage and not put back into stock.'),
        ),
    ]
