# Generated by Django 6.0.5 on 2026-07-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
