# Generated by Django 6.0.5 on 2026-07-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_pricelist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='course',
        ),
        migrations.DeleteModel(
            name='MenuCourse',
        ),
    ]
