# Generated by Django 6.0.5 on 2026-07-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menuitem_course_delete_menucourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name']},
        ),
    ]
