# Generated by Django 6.0.5 on 2026-08-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_alter_menu_unique_together_alter_menu_name_and_more"),
        # Cross-app FKs to PriceList must be dropped before the model is deleted.
        ("orders", "0006_remove_kot_naming_series_remove_orderitem_price_list_and_more"),
        ("settings", "0018_remove_restaurant_branch_remove_posprofile_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='menu',
        ),
        migrations.DeleteModel(
            name='ItemPrice',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
