# Generated by Django 6.0.5 on 2026-08-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_warehouse_unique_together_alter_warehouse_name_and_more'),
        ('menu', '0006_remove_pricelist_menu_delete_itemprice_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='menu_item_rate_gte_zero'),
        ),
    ]
