# Generated by Django 6.0.5 on 2026-08-17 10:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('year_start_date', models.DateField()),
                ('year_end_date', models.DateField()),
                ('disabled', models.BooleanField(default=False)),
                ('is_short_year', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['year_start_date'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_group', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.costcenter')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_type', models.CharField(choices=[('JOURNAL', 'Journal Entry'), ('CASH', 'Cash Entry'), ('BANK', 'Bank Entry'), ('WRITE_OFF', 'Write Off'), ('OPENING', 'Opening Entry')], default='JOURNAL', max_length=20)),
                ('posting_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('write_off_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_opening', models.BooleanField(default=False, editable=False)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-posting_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_group', models.BooleanField(default=False)),
                ('root_type', models.CharField(blank=True, choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('report_type', models.CharField(blank=True, choices=[('BALANCE_SHEET', 'Balance Sheet'), ('PROFIT_AND_LOSS', 'Profit & Loss')], max_length=15)),
                ('account_type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Stock', 'Stock'), ('Income Account', 'Income Account'), ('Expense Account', 'Expense Account'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Round Off', 'Round Off'), ('Equity', 'Equity')], max_length=30)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('freeze_account', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.ledgeraccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_rows', to='accounting.costcenter')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.journalentry')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_rows', to='accounting.ledgeraccount')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GLEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting_date', models.DateField()),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('against', models.CharField(blank=True, max_length=200)),
                ('voucher_type', models.CharField(max_length=50)),
                ('voucher_no', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False, editable=False)),
                ('is_opening', models.BooleanField(default=False)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries', to='accounting.costcenter')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.fiscalyear')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.ledgeraccount')),
            ],
            options={
                'ordering': ['-posting_date', '-pk'],
                'indexes': [models.Index(fields=['account', 'posting_date'], name='accounting__account_94e3c3_idx'), models.Index(fields=['voucher_type', 'voucher_no'], name='accounting__voucher_ba37a0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='accounting_gl_amounts_non_negative'), models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _connector='OR'), name='accounting_gl_single_side')],
            },
        ),
    ]
