# Generated by Django 6.0.5 on 2026-08-19 05:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0026_itemgroup_expense_account_itemgroup_income_account_and_more'),
        ('payments', '0005_payment_gl_mapping_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.CharField(max_length=200, unique=True)),
                ('supplier_type', models.CharField(choices=[('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual')], default='COMPANY', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('payable_account', models.ForeignKey(blank=True, help_text='Per-supplier accounts-payable account override; falls back to the Restaurant default.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Payable account')),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('posting_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(default=django.utils.timezone.localdate)),
                ('bill_no', models.CharField(blank=True, max_length=100)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('purchase_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='inventory.purchasereceipt')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.supplier')),
            ],
            options={
                'ordering': ['-posting_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('received_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('amount_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_lines', to='accounting.costcenter')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='accounting.ledgeraccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.supplierinvoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_items', to='inventory.item')),
                ('source_receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_lines', to='inventory.purchasereceiptitem')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('posting_date', models.DateField(default=django.utils.timezone.localdate)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='payments.modeofpayment')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.supplier')),
            ],
            options={
                'ordering': ['-posting_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='accounting.supplierinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.supplierpayment')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
