# Generated by Django 6.0.5 on 2026-08-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_backfill_suppliers_from_receipts'),
        ('inventory', '0027_purchasereceipt_supplier'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source_receipt_line__isnull', False)), fields=('source_receipt_line',), name='accounting_invoice_item_unique_receipt_line'),
        ),
    ]
