# Generated by Django 6.0.5 on 2026-08-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_invoice_unique_receipt_line'),
        ('settings', '0029_remove_restaurant_cost_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glentry',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='supplierinvoiceitem',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='journalentryaccount',
            name='cost_center',
        ),
        migrations.DeleteModel(
            name='CostCenter',
        ),
    ]
