# Generated by Django 6.0.5 on 2026-08-28 02:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_glentry_cost_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierinvoiceitem',
            name='expense_account',
        ),
        migrations.CreateModel(
            name='SupplierInvoiceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounting.supplierinvoice')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
