# Generated by Django 6.0.5 on 2026-09-01 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_supplierinvoiceitem_expense_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='payable_account',
            field=models.ForeignKey(blank=True, help_text='The account used to track what you owe this supplier. Leave blank to use the default payable account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Payable account'),
        ),
    ]
