# Generated by Django 6.0.5 on 2026-09-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_rename_root_type_and_drop_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='write_off_amount',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='voucher_type',
            field=models.CharField(choices=[('JOURNAL', 'Journal Entry'), ('CASH', 'Cash Entry'), ('BANK', 'Bank Entry'), ('OPENING', 'Opening Entry')], default='JOURNAL', max_length=20),
        ),
    ]
