# Generated by Django 6.0.5 on 2026-07-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_seed_payment_modes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentglmapping',
            options={'ordering': ['mode_of_payment__name']},
        ),
        migrations.AlterUniqueTogether(
            name='paymentglmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modeofpayment',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentglmapping',
            name='mode_of_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gl_mapping', to='payments.modeofpayment'),
        ),
        migrations.RemoveField(
            model_name='paymentglmapping',
            name='company',
        ),
    ]
