# Generated by Django 6.0.5 on 2026-08-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentglmapping_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modeofpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='payments_one_default_mode'),
        ),
    ]
