# Generated by Django 6.0.5 on 2026-09-01 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_supplier_payable_account'),
        ('payments', '0005_payment_gl_mapping_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentglmapping',
            name='default_account',
            field=models.ForeignKey(help_text='The account where payments made with this method are recorded.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_gl_mappings', to='accounting.ledgeraccount', verbose_name='Default account'),
        ),
    ]
