# Generated by Django 6.0.5 on 2026-07-18 09:12

from django.db import migrations


def create_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="RestPOS Manager")
    Group.objects.get_or_create(name="RestPOS Cashier")


def remove_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["RestPOS Manager", "RestPOS Cashier"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_avatar"),
    ]

    operations = [
        migrations.RunPython(create_roles, reverse_code=remove_roles),
    ]
