# Generated by Django 6.0.5 on 2026-07-17 10:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('MATERIAL_RECEIPT', 'Material Receipt'), ('MATERIAL_ISSUE', 'Material Issue'), ('MATERIAL_TRANSFER', 'Material Transfer'), ('REPACK', 'Repack')], max_length=30)),
                ('posting_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-posting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('RECONCILIATION', 'Stock Reconciliation')], default='RECONCILIATION', max_length=20)),
                ('posting_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-posting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('FOOD', 'Food'), ('DRINKS', 'Drinks')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('description', models.TextField(blank=True)),
                ('disabled', models.BooleanField(default=False)),
                ('is_stock_item', models.BooleanField(default=True)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('MOVING_AVERAGE', 'Moving Average')], default='FIFO', max_length=20)),
                ('has_batch_no', models.BooleanField(default=False)),
                ('has_expiry_date', models.BooleanField(default=False)),
                ('shelf_life_in_days', models.IntegerField(blank=True, null=True)),
                ('has_variants', models.BooleanField(default=False)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('end_of_life', models.DateField(blank=True, null=True)),
                ('standard_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variant_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='inventory.item')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('batch_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('barcode_type', models.CharField(blank=True, max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='inventory.item')),
            ],
            options={
                'ordering': ['barcode'],
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_group', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.itemgroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemgroup'),
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='inventory.item')),
            ],
            options={
                'unique_together': {('parent_item',)},
            },
        ),
        migrations.CreateModel(
            name='ProductBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.productbundle')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='stock_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.uom'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_group', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='settings.branch')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['branch__name', 'name'],
                'unique_together': {('name', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='StockReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('valuation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockreconciliation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='StockEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10)),
                ('basic_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.batch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_details', to='inventory.item')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockentry')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.uom')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_details', to='inventory.warehouse')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_details', to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockentry',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_stock_entries', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_stock_entries', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_items', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='ItemUOMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions', to='inventory.item')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.uom')),
            ],
            options={
                'unique_together': {('item', 'uom')},
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting_datetime', models.DateTimeField(auto_now_add=True)),
                ('voucher_type', models.CharField(max_length=50)),
                ('voucher_no', models.CharField(max_length=100)),
                ('voucher_detail_no', models.CharField(blank=True, max_length=100)),
                ('actual_qty', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('qty_after_transaction', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('incoming_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('outgoing_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('valuation_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('stock_value', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('stock_queue', models.TextField(blank=True, default='')),
                ('is_cancelled', models.BooleanField(default=False, editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-posting_datetime'],
                'indexes': [models.Index(fields=['item', 'warehouse', '-posting_datetime'], name='inventory_s_item_id_35c443_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReorderLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_levels', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('item', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('valuation_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('stock_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
