# Generated by Django 6.0.5 on 2026-07-17 17:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_delivery_note', models.CharField(blank=True, max_length=100)),
                ('posting_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('accepted_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventory.warehouse')),
                ('rejected_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_receipts', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-posting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejected_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('accepted_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.batch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_items', to='inventory.item')),
                ('purchase_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchasereceipt')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.uom')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_item_warehouses', to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
