# Generated by Django 6.0.5 on 2026-07-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchasereceipt_purchasereceiptitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbundleitem',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='productbundleitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='ProductBundle',
        ),
        migrations.DeleteModel(
            name='ProductBundleItem',
        ),
    ]
