# Generated by Django 6.0.5 on 2026-07-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='parent',
        ),
    ]
