# Generated by Django 6.0.5 on 2026-07-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_warehouse_grouping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='is_rejected',
        ),
    ]
