# Generated by Django 6.0.5 on 2026-07-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgroup',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='itemgroup',
            name='parent',
        ),
    ]
