# Generated by Django 6.0.5 on 2026-07-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_flatten_item_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uom',
            name='is_active',
        ),
    ]
