# Generated by Django 6.0.5 on 2026-07-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_seed_item_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentrydetail',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='purchasereceiptitem',
            name='batch',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='standard_rate',
            new_name='last_purchase_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='end_of_life',
        ),
        migrations.RemoveField(
            model_name='item',
            name='has_batch_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='has_expiry_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lead_time_days',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shelf_life_in_days',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
