# Generated by Django 6.0.5 on 2026-07-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_stockentrydetail_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBarcode',
        ),
    ]
