# Generated by Django 6.0.5 on 2026-07-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentrydetail',
            name='conversion_factor',
        ),
        migrations.DeleteModel(
            name='ItemUOMConversion',
        ),
    ]
