# Generated by Django 6.0.5 on 2026-07-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_uom_conversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReorderLevel',
        ),
    ]
