# Generated by Django 6.0.5 on 2026-07-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
