# Generated by Django 6.0.5 on 2026-07-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_hardcode_fifo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='from_warehouse',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='to_warehouse',
        ),
        migrations.RemoveField(
            model_name='stockentrydetail',
            name='uom',
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='purpose',
            field=models.CharField(choices=[('MATERIAL_RECEIPT', 'Material Receipt'), ('MATERIAL_ISSUE', 'Material Issue'), ('MATERIAL_TRANSFER', 'Material Transfer')], max_length=30),
        ),
    ]
