# Generated by Django 6.0.5 on 2026-07-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_simplify_stock_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereceiptitem',
            name='uom',
        ),
    ]
