# Generated by Django 6.0.5 on 2026-07-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_purchasereceiptitem_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereceipt',
            name='rejected_warehouse',
        ),
        migrations.RemoveField(
            model_name='purchasereceiptitem',
            name='accepted_qty',
        ),
        migrations.RemoveField(
            model_name='purchasereceiptitem',
            name='rejected_qty',
        ),
    ]
