# Generated by Django 6.0.5 on 2026-07-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_purchasereceipt_rejected_warehouse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereceipt',
            old_name='accepted_warehouse',
            new_name='warehouse',
        ),
        migrations.RemoveField(
            model_name='purchasereceiptitem',
            name='warehouse',
        ),
    ]
