# Generated by Django 6.0.5 on 2026-07-24 03:51

from django.db import migrations, models


def backfill_sales_purchase_flags(apps, schema_editor):
    Item = apps.get_model("inventory", "Item")
    MenuItem = apps.get_model("menu", "MenuItem")

    # Items already on a menu → sellable (templates will be cleared below).
    on_menu_ids = MenuItem.objects.values_list("item_id", flat=True).distinct()
    Item.objects.filter(pk__in=on_menu_ids).update(is_sales_item=True)

    # Templates never sell/purchase/stock.
    Item.objects.filter(has_variants=True).update(
        is_sales_item=False,
        is_purchase_item=False,
        is_stock_item=False,
    )

    # Purchase: supplies/raw descriptions and non-sales stock items.
    Item.objects.filter(description__icontains="Raw / bulk").update(is_purchase_item=True)
    Item.objects.filter(item_group__name="Supplies").update(is_purchase_item=True)
    # Bought-in drinks groups
    Item.objects.filter(
        item_group__name__in=["Soft Drinks", "Beer", "Spirits", "Wine", "Water", "Juice & Malt"],
        has_variants=False,
    ).update(is_purchase_item=True, is_sales_item=True)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_rename_accepted_warehouse_purchasereceipt_warehouse_and_more"),
        ("menu", "0003_remove_menuitem_course_delete_menucourse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouse",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="item",
            name="is_purchase_item",
            field=models.BooleanField(
                default=False, help_text="If true, this item may appear on purchase receipts."
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_sales_item",
            field=models.BooleanField(
                default=False,
                help_text="If true, this item may be added to a menu and sold on the POS.",
            ),
        ),
        migrations.RunPython(backfill_sales_purchase_flags, migrations.RunPython.noop),
    ]
