# Generated by Django 6.0.5 on 2026-07-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_item_sales_purchase_flags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockreconciliationitem",
            name="warehouse",
        ),
    ]
