# Generated by Django 6.0.5 on 2026-07-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_reconciliation_item_warehouse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='branch',
        ),
    ]
