# Generated by Django 6.0.5 on 2026-08-03 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_warehouse_unique_together_alter_warehouse_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreconciliation',
            name='reason',
            field=models.CharField(choices=[('PHYSICAL_COUNT', 'Physical Count'), ('CONSUMPTION', 'Consumption'), ('WASTE_DAMAGE', 'Waste / Damage'), ('CORRECTION', 'Correction')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='purpose',
            field=models.CharField(choices=[('MATERIAL_RECEIPT', 'Material Receipt'), ('MATERIAL_TRANSFER', 'Material Transfer')], max_length=30),
        ),
    ]
