# Generated by Django 6.0.5 on 2026-08-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_backfill_stock_reconciliation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreconciliation',
            name='reason',
            field=models.CharField(
                choices=[
                    ('PHYSICAL_COUNT', 'Physical Count'),
                    ('CONSUMPTION', 'Consumption'),
                    ('WASTE_DAMAGE', 'Waste / Damage'),
                    ('CORRECTION', 'Correction'),
                ],
                max_length=20,
            ),
        ),
    ]
