# Generated by Django 6.0.5 on 2026-08-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_stockreconciliation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='items/default-item.png', upload_to='items/'),
        ),
    ]
