# Generated by Django 6.0.5 on 2026-08-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0025_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Expense account'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Income account'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Credited with the stock value of settle-time drink deductions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Account'),
        ),
    ]
