# Generated by Django 6.0.5 on 2026-08-19 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_supplier_supplierinvoice_supplierinvoiceitem_and_more'),
        ('inventory', '0026_itemgroup_expense_account_itemgroup_income_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Optional link to the Supplier master; the receipt keeps its free-text name for quick entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts', to='accounting.supplier', verbose_name='Supplier'),
        ),
    ]
