# Generated by Django 6.0.5 on 2026-08-25 04:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_purchasereceipt_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='stock_value',
        ),
        migrations.RemoveField(
            model_name='stockledgerentry',
            name='actual_qty',
        ),
        migrations.RemoveField(
            model_name='stockledgerentry',
            name='incoming_rate',
        ),
        migrations.RemoveField(
            model_name='stockledgerentry',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='stockledgerentry',
            name='outgoing_rate',
        ),
        migrations.RemoveField(
            model_name='stockledgerentry',
            name='qty_after_transaction',
        ),
        migrations.RemoveField(
            model_name='stockledgerentry',
            name='stock_queue',
        ),
        migrations.RemoveField(
            model_name='stockledgerentry',
            name='stock_value',
        ),
        migrations.RemoveField(
            model_name='stockledgerentry',
            name='valuation_rate',
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='posting_date',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='reversal_of_sle',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.stockledgerentry'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='stock_value_change',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='unit_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='variance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='variance_type',
            field=models.CharField(blank=True, choices=[('CANCELLATION_WAC', 'Cancellation WAC'), ('SALE_RETURN', 'Sale Return')], default='', editable=False, max_length=20),
        ),
    ]
