# Generated by Django 6.0.5 on 2026-08-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_pwac_clean_slate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='safety_stock',
        ),
    ]
