# Generated by Django 6.0.5 on 2026-09-01 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_supplier_payable_account'),
        ('inventory', '0031_align_item_flags_with_lifecycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='default_warehouse',
        ),
        migrations.AlterField(
            model_name='item',
            name='is_purchase_item',
            field=models.BooleanField(default=False, help_text='Allow this item to be added to purchase receipts.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_sales_item',
            field=models.BooleanField(default=False, help_text='Allow this item to be added to menus and sold at the POS.'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Link this receipt to a supplier record, if you keep one. The supplier name is still saved either way.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts', to='accounting.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='account',
            field=models.ForeignKey(blank=True, help_text='The account that holds the value of stock in this warehouse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Account'),
        ),
    ]
