# Generated by Django 6.0.5 on 2026-09-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_remove_item_default_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgroup',
            name='expense_account',
        ),
        migrations.RemoveField(
            model_name='itemgroup',
            name='income_account',
        ),
    ]
