# Generated by Django 6.0.5 on 2026-09-06 14:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_remove_itemgroup_expense_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.uom'),
        ),
        migrations.CreateModel(
            name='ItemUOMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions', to='inventory.item')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.uom')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('conversion_factor__gt', 0)), name='inventory_itemuomconversion_factor_gt_0')],
                'unique_together': {('item', 'uom')},
            },
        ),
    ]
