# Generated by Django 6.0.5 on 2026-09-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0035_backfill_purchasereceiptitem_uom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasereceiptitem",
            name="uom",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.uom"),
        ),
    ]
