# Generated by Django 6.0.5 on 2026-09-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_purchasereceiptitem_uom_required'),
        ('payments', '0006_alter_paymentglmapping_default_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='mode_of_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='payments.modeofpayment'),
        ),
    ]
