# Generated by Django 6.0.5 on 2026-09-09 05:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_backfill_stockentrydetail_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreconciliation',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='purchasereceiptitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockreconciliation',
            name='reason',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('ADJUSTMENT', 'Adjustment'), ('CONSUMPTION', 'Consumption'), ('WASTE_DAMAGE', 'Waste / Damage'), ('PHYSICAL_COUNT', 'Physical Count'), ('CORRECTION', 'Correction')], max_length=20),
        ),
    ]
