# Generated by Django 6.0.5 on 2026-09-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_remove_stockreconciliation_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreconciliation',
            name='reason',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('ADJUSTMENT', 'Adjustment'), ('CONSUMPTION', 'Consumption'), ('WASTE_DAMAGE', 'Waste / Damage')], max_length=20),
        ),
    ]
