# Generated by Django 6.0.5 on 2026-07-17 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('make_aggregator_unpaid', models.BooleanField(default=False)),
                ('no_aggregator_taxes', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(blank=True, choices=[('AC', 'AC'), ('NON_AC', 'Non-AC')], max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='settings.branch')),
            ],
            options={
                'ordering': ['branch__name', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=200)),
                ('invoice_series_prefix', models.CharField(default='REST-', max_length=20)),
                ('aggregator_series_prefix', models.CharField(blank=True, default='AGR-', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='settings.branch')),
                ('default_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='settings.room')),
            ],
            options={
                'ordering': ['branch__name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('no_of_seats', models.IntegerField(blank=True, null=True)),
                ('minimum_seating', models.IntegerField(blank=True, null=True)),
                ('table_shape', models.CharField(blank=True, choices=[('RECTANGLE', 'Rectangle'), ('SQUARE', 'Square'), ('CIRCLE', 'Circle')], max_length=20)),
                ('is_take_away', models.BooleanField(default=False)),
                ('occupied', models.BooleanField(default=False, editable=False)),
                ('latest_invoice_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('layout_x', models.FloatField(blank=True, null=True)),
                ('layout_y', models.FloatField(blank=True, null=True)),
                ('layout_width', models.FloatField(blank=True, null=True)),
                ('layout_height', models.FloatField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='settings.branch')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='settings.room')),
            ],
            options={
                'ordering': ['room__name', 'name'],
                'unique_together': {('room', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserRoomAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_room_assignments', to='settings.branch')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='settings.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'unique_together': {('user', 'room')},
            },
        ),
    ]
