# Generated by Django 6.0.5 on 2026-07-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_restaurant_active_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='make_aggregator_unpaid',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='no_aggregator_taxes',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='aggregator_series_prefix',
        ),
    ]
