# Generated by Django 6.0.5 on 2026-07-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_aggregator_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
