# Generated by Django 6.0.5 on 2026-07-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_room_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['company']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
    ]
