# Generated by Django 6.0.5 on 2026-07-27 23:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0019_item_sales_purchase_flags'),
        ('menu', '0004_alter_menu_options'),
        ('payments', '0002_seed_payment_modes'),
        ('settings', '0005_alter_restaurant_options_alter_room_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('disabled', models.BooleanField(default=False)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('tax_category', models.CharField(blank=True, max_length=100)),
                ('cost_center', models.CharField(blank=True, max_length=200)),
                ('income_account', models.CharField(blank=True, max_length=200)),
                ('expense_account', models.CharField(blank=True, max_length=200)),
                ('write_off_account', models.CharField(blank=True, max_length=200)),
                ('write_off_cost_center', models.CharField(blank=True, max_length=200)),
                ('write_off_limit', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('account_for_change_amount', models.CharField(blank=True, max_length=200)),
                ('set_grand_total_to_default_mop', models.BooleanField(default=True)),
                ('allow_partial_payment', models.BooleanField(default=False)),
                ('apply_discount_on', models.CharField(choices=[('GRAND_TOTAL', 'Grand Total'), ('NET_TOTAL', 'Net Total')], default='GRAND_TOTAL', max_length=15)),
                ('enable_discount', models.BooleanField(default=False)),
                ('action_on_new_invoice', models.CharField(choices=[('ALWAYS_ASK', 'Always Ask'), ('SAVE_AND_LOAD_NEW', 'Save Changes and Load New'), ('DISCARD_AND_LOAD_NEW', 'Discard Changes and Load New')], default='ALWAYS_ASK', max_length=40)),
                ('validate_stock_on_save', models.BooleanField(default=False)),
                ('hide_images', models.BooleanField(default=False)),
                ('hide_unavailable_items', models.BooleanField(default=False)),
                ('auto_add_item_to_cart', models.BooleanField(default=False)),
                ('allow_rate_change', models.BooleanField(default=False)),
                ('allow_discount_change', models.BooleanField(default=False)),
                ('allow_warehouse_change', models.BooleanField(default=False)),
                ('print_receipt_on_order_complete', models.BooleanField(default=False)),
                ('view_all_status', models.BooleanField(default=False)),
                ('paid_limit', models.IntegerField(default=20)),
                ('edit_order_type', models.BooleanField(default=False)),
                ('remove_items', models.BooleanField(default=False)),
                ('show_image', models.BooleanField(default=True)),
                ('require_daily_pos_close', models.BooleanField(default=False)),
                ('table_attention_time', models.IntegerField(default=0)),
                ('multiple_cashier', models.BooleanField(default=False)),
                ('kot_naming_series', models.CharField(default='KOT-####', max_length=50)),
                ('reset_order_number_daily', models.BooleanField(default=False)),
                ('kot_warning_time', models.IntegerField(default=15)),
                ('notify_kot_delay', models.BooleanField(default=False)),
                ('enable_kot_reprint', models.BooleanField(default=False)),
                ('reprint_kot_format', models.CharField(blank=True, max_length=100)),
                ('print_format', models.CharField(blank=True, max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_profiles', to='settings.branch')),
                ('item_groups', models.ManyToManyField(blank=True, related_name='pos_profiles', to='inventory.itemgroup')),
                ('notification_recipients', models.ManyToManyField(blank=True, related_name='delay_notification_profiles', to='auth.group')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_profiles', to='settings.restaurant')),
                ('role_allowed_for_billing', models.ManyToManyField(blank=True, related_name='billing_profiles', to='auth.group')),
                ('role_restricted_for_table_order', models.ManyToManyField(blank=True, related_name='table_order_restricted_profiles', to='auth.group')),
                ('selling_price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_profiles', to='menu.pricelist')),
                ('transfer_role_permissions', models.ManyToManyField(blank=True, related_name='transfer_profiles', to='auth.group')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_profiles', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POSProfilePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('allow_in_returns', models.BooleanField(default=False)),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_links', to='payments.modeofpayment')),
                ('pos_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='settings.posprofile')),
            ],
            options={
                'ordering': ['mode_of_payment__name'],
                'unique_together': {('pos_profile', 'mode_of_payment')},
            },
        ),
        migrations.AddField(
            model_name='posprofile',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='pos_profiles', through='settings.POSProfilePayment', to='payments.modeofpayment'),
        ),
        migrations.CreateModel(
            name='POSProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_main_cashier', models.BooleanField(default=False)),
                ('pos_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='settings.posprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'unique_together': {('pos_profile', 'user')},
            },
        ),
        migrations.AddField(
            model_name='posprofile',
            name='applicable_users',
            field=models.ManyToManyField(blank=True, related_name='pos_profiles', through='settings.POSProfileUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaxTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('company', models.CharField(max_length=200)),
                ('tax_category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'company')},
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.CharField(choices=[('ACTUAL', 'Actual'), ('ON_NET_TOTAL', 'On Net Total'), ('ON_PREVIOUS_ROW_AMOUNT', 'On Previous Row Amount'), ('ON_PREVIOUS_ROW_TOTAL', 'On Previous Row Total'), ('ON_ITEM_QUANTITY', 'On Item Quantity')], default='ON_NET_TOTAL', max_length=30)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('account_head', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=200)),
                ('included_in_print_rate', models.BooleanField(default=False)),
                ('row_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tax_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='settings.taxtemplate')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='posprofile',
            name='taxes_and_charges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_profiles', to='settings.taxtemplate'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='default_tax_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='settings.taxtemplate'),
        ),
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('FOOD', 'Food'), ('DRINKS', 'Drinks')], max_length=10)),
                ('block_takeaway_kot', models.BooleanField(default=False)),
                ('printer_ip', models.CharField(blank=True, max_length=50)),
                ('printer_paper_width', models.CharField(choices=[('WIDTH_58MM', '58mm'), ('WIDTH_80MM', '80mm')], default='WIDTH_80MM', max_length=10)),
                ('printer_cut_mode', models.CharField(choices=[('FULL_CUT', 'Full Cut'), ('PARTIAL_CUT', 'Partial Cut'), ('NO_CUT', 'No Cut')], default='FULL_CUT', max_length=15)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_units', to='settings.branch')),
                ('pos_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_units', to='settings.posprofile')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_units', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'branch')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='posprofile',
            unique_together={('name', 'branch')},
        ),
    ]
