# Generated by Django 6.0.5 on 2026-07-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_phase6_pos_profile_production_unit_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posprofile',
            name='tax_category',
        ),
        migrations.RemoveField(
            model_name='posprofile',
            name='taxes_and_charges',
        ),
    ]
