# Generated by Django 6.0.5 on 2026-07-28 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_remove_pos_profile_tax_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posprofile',
            unique_together={('restaurant',)},
        ),
        migrations.AlterField(
            model_name='posprofile',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pos_profiles', to='settings.restaurant'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='posprofile',
            name='applicable_users',
        ),
        migrations.DeleteModel(
            name='POSProfileUser',
        ),
    ]
