# Generated by Django 6.0.5 on 2026-07-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_single_pos_profile_per_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posprofile',
            name='multiple_cashier'),
    ]
