# Generated by Django 6.0.5 on 2026-07-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_remove_posprofile_multiple_cashier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posprofile',
            name='kot_warning_time'),
        migrations.RemoveField(
            model_name='posprofile',
            name='notification_recipients'),
        migrations.RemoveField(
            model_name='posprofile',
            name='notify_kot_delay'),
        migrations.RemoveField(
            model_name='posprofile',
            name='role_allowed_for_billing'),
        migrations.RemoveField(
            model_name='posprofile',
            name='role_restricted_for_table_order'),
        migrations.RemoveField(
            model_name='posprofile',
            name='transfer_role_permissions'),
    ]
