# Generated by Django 6.0.5 on 2026-07-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_remove_posprofile_kot_warning_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posprofile',
            name='allow_discount_change'),
        migrations.RemoveField(
            model_name='posprofile',
            name='allow_warehouse_change'),
        migrations.RemoveField(
            model_name='posprofile',
            name='apply_discount_on'),
        migrations.RemoveField(
            model_name='posprofile',
            name='enable_discount'),
        migrations.RemoveField(
            model_name='posprofile',
            name='table_attention_time'),
    ]
