# Generated by Django 6.0.5 on 2026-07-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_remove_posprofile_allow_discount_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posprofile',
            name='allow_partial_payment'),
        migrations.RemoveField(
            model_name='posprofile',
            name='allow_rate_change'),
    ]
