# Generated by Django 6.0.5 on 2026-07-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_remove_posprofile_allow_partial_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoomAssignment'),
    ]
