# Generated by Django 6.0.5 on 2026-07-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0013_delete_userroomassignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="default_room",
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name="Table",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
