# Generated by Django 6.0.5 on 2026-07-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0013_delete_userroomassignment"),
        # Order.room FK created in orders/0001 and removed in orders/0005 must both
        # run before Room is deleted — otherwise fresh test-DB replays fail.
        ("orders", "0005_remove_order_room_remove_order_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="default_room",
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name="Table",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
