# Generated by Django 6.0.5 on 2026-07-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_taxes_and_charges_template_and_more'),
        ('settings', '0014_remove_table_room_remove_restaurant_default_room_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxtemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='default_tax_template',
        ),
        migrations.DeleteModel(
            name='TaxRate',
        ),
        migrations.DeleteModel(
            name='TaxTemplate',
        ),
    ]
