# Generated by Django 6.0.5 on 2026-07-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_reconciliation_item_warehouse'),
        ('settings', '0015_alter_taxtemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_restaurants', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reset_order_number_daily',
            field=models.BooleanField(default=False),
        ),
    ]
