# Generated by Django 6.0.5 on 2026-07-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_warehouse_unique_together_alter_warehouse_name_and_more'),
        ('menu', '0005_alter_menu_unique_together_alter_menu_name_and_more'),
        ('orders', '0009_remove_order_orders_orde_branch__c40543_idx_and_more'),
        ('settings', '0017_single_location_data'),
        ('staff', '0004_remove_posclosingentry_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='posprofile',
            name='branch',
        ),
        migrations.AlterUniqueTogether(
            name='posprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='posprofile',
            name='item_groups',
        ),
        migrations.RemoveField(
            model_name='posprofile',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='posprofile',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='posprofile',
            name='selling_price_list',
        ),
        migrations.RemoveField(
            model_name='posprofile',
            name='warehouse',
        ),
        migrations.AlterUniqueTogether(
            name='productionunit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productionunit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='POSProfilePayment',
        ),
        migrations.RemoveField(
            model_name='productionunit',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='productionunit',
            name='pos_profile',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='POSProfile',
        ),
    ]
