# Generated by Django 6.0.5 on 2026-07-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_remove_restaurant_branch_remove_posprofile_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='currency',
        ),
    ]
