# Generated by Django 6.0.5 on 2026-08-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_remove_restaurant_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='reset_order_number_daily',
        ),
    ]
