# Generated by Django 6.0.5 on 2026-08-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_remove_restaurant_reset_order_number_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_open_drafts',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
