# Generated by Django 6.0.5 on 2026-08-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_restaurant_max_open_drafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='max_open_drafts',
            field=models.PositiveIntegerField(default=50, help_text='Maximum normal POS drafts allowed on one active shift.'),
        ),
    ]
