# Generated by Django 6.0.5 on 2026-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_warehouse_unique_together_alter_warehouse_name_and_more'),
        ('settings', '0022_alter_restaurant_max_open_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productionunit',
            constraint=models.UniqueConstraint(fields=('department',), name='settings_one_production_unit_per_department'),
        ),
    ]
