# Generated by Django 6.0.5 on 2026-08-03 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_stockreconciliation_reason_and_more'),
        ('settings', '0023_restaurant_singleton_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='store_warehouse',
            field=models.ForeignKey(blank=True, help_text='Central Store used for all receipts and as the source of material transfers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_for_restaurants', to='inventory.warehouse', verbose_name='Central Store warehouse'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse used for Bar stock and POS drink deductions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_restaurants', to='inventory.warehouse', verbose_name='Bar / POS sales warehouse'),
        ),
    ]
