# Generated by Django 6.0.5 on 2026-08-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_restaurant_store_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pos_allow_full_history',
            field=models.BooleanField(default=False, help_text='When enabled, cashiers can use All/Returns/Cancelled history filters. Managers always can.'),
        ),
    ]
