# Generated by Django 6.0.5 on 2026-08-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('settings', '0025_review_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionunit',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='Departmental income hook — Kitchen = FOOD income, Bar = DRINKS income.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Income account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='account_for_change_amount',
            field=models.ForeignKey(blank=True, help_text='The cash account whose settle-time payment rows are reduced by the change given.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Account for change amount'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cash_over_short_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Cash over/short account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cash_shortage_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Cash shortage account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Cost center stamped on order GL postings.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.costcenter', verbose_name='Default cost center'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='default_expense_account',
            field=models.ForeignKey(blank=True, help_text='Fallback expense account for COGS when the item group has none.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default expense account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='default_income_account',
            field=models.ForeignKey(blank=True, help_text='Fallback income account for orders (item group and production unit accounts take precedence).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default income account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='round_off_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Round-off account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='variance_approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Absolute cash variance that requires a manager note to close. Blank = no approval gate.', max_digits=14, null=True, verbose_name='Variance approval threshold'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wastage_account',
            field=models.ForeignKey(blank=True, help_text='Expense account for non-restockable returned drinks.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Wastage account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='write_off_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Write-off account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='write_off_cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.costcenter', verbose_name='Write-off cost center'),
        ),
    ]
