# Generated by Django 6.0.5 on 2026-08-19 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_supplier_supplierinvoice_supplierinvoiceitem_and_more'),
        ('settings', '0026_productionunit_income_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='default_payable_account',
            field=models.ForeignKey(blank=True, help_text='Accounts-payable account credited by supplier invoices and debited by supplier payments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default payable account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='default_stock_in_hand_account',
            field=models.ForeignKey(blank=True, help_text='Stock account debited by supplier invoice stock lines when the item group has no expense account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default stock-in-hand account'),
        ),
    ]
