# Generated by Django 6.0.5 on 2026-08-25 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_invoice_unique_receipt_line'),
        ('settings', '0027_restaurant_default_payable_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='inventory_price_variance_account',
            field=models.ForeignKey(blank=True, help_text='Expense account for cancellation WAC drift (receipt cancellations only; sale-return variance posts to COGS).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Inventory price variance account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='stock_received_but_not_billed_account',
            field=models.ForeignKey(blank=True, help_text='Liability account credited by goods receipts and debited by linked supplier invoices.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Stock received but not billed (GRNI)'),
        ),
    ]
