# Generated by Django 6.0.5 on 2026-08-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_restaurant_inventory_price_variance_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='write_off_cost_center',
        ),
    ]
