# Generated by Django 6.0.5 on 2026-08-28 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_supplierinvoiceitem_expense_account_and_more'),
        ('settings', '0029_remove_restaurant_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='default_supplier_expense_account',
            field=models.ForeignKey(blank=True, help_text='Expense account debited by supplier invoice expense lines.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default supplier expense account'),
        ),
    ]
