# Generated by Django 6.0.5 on 2026-09-01 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_supplier_payable_account'),
        ('inventory', '0032_remove_item_default_warehouse_and_more'),
        ('settings', '0030_restaurant_default_supplier_expense_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionunit',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='The income account used for sales from this station.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Income account'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='account_for_change_amount',
            field=models.ForeignKey(blank=True, help_text='The cash account used to record change given back to customers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Account for change amount'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='default_expense_account',
            field=models.ForeignKey(blank=True, help_text='The expense account used to record the cost of drinks sold when no category account is set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default expense account'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='default_income_account',
            field=models.ForeignKey(blank=True, help_text='The income account used for sales when no category or kitchen/bar account is set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default income account'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='default_payable_account',
            field=models.ForeignKey(blank=True, help_text='The account used to track amounts owed to suppliers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default payable account'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='default_stock_in_hand_account',
            field=models.ForeignKey(blank=True, help_text='The stock account used for supplier invoice items when no category account is set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default stock-in-hand account'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='default_supplier_expense_account',
            field=models.ForeignKey(blank=True, help_text='The expense account used for non-stock costs on supplier invoices.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Default supplier expense account'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, help_text='The warehouse that holds bar stock and supplies drink sales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_restaurants', to='inventory.warehouse', verbose_name='Bar / POS sales warehouse'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='inventory_price_variance_account',
            field=models.ForeignKey(blank=True, help_text='The expense account used when cancelled receipts leave a small difference in stock value.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Inventory price variance account'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='max_open_drafts',
            field=models.PositiveIntegerField(default=50, help_text='The maximum number of open orders allowed on a shift at one time.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='stock_received_but_not_billed_account',
            field=models.ForeignKey(blank=True, help_text='The account that holds the value of goods received before the supplier invoice arrives.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Stock received but not billed (GRNI)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='store_warehouse',
            field=models.ForeignKey(blank=True, help_text='The main store where all goods are received before moving to the kitchen or bar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_for_restaurants', to='inventory.warehouse', verbose_name='Central Store warehouse'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='variance_approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash difference that requires a manager note before a shift can be closed. Leave blank to allow any variance without a note.', max_digits=14, null=True, verbose_name='Variance approval threshold'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='wastage_account',
            field=models.ForeignKey(blank=True, help_text='The expense account used when returned drinks cannot be put back into stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Wastage account'),
        ),
    ]
