# Generated by Django 6.0.5 on 2026-09-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_alter_productionunit_income_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='write_off_account',
        ),
    ]
