# Generated by Django 6.0.5 on 2026-09-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_journalentry_write_off_amount_and_more'),
        ('settings', '0032_remove_restaurant_write_off_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='stock_adjustment_account',
            field=models.ForeignKey(blank=True, help_text='The expense account used for stock adjustments (count corrections up or down).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Stock adjustment account'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='temporary_opening_account',
            field=models.ForeignKey(blank=True, help_text='The equity account credited when opening stock is first seeded into a fresh warehouse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Temporary opening account'),
        ),
    ]
