# Generated by Django 6.0.5 on 2026-09-09 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_journalentry_write_off_amount_and_more'),
        ('settings', '0033_restaurant_stock_adjustment_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionunit',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='The expense account used for cost of goods sold from this station.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount', verbose_name='Expense account'),
        ),
    ]
