# Generated by Django 6.0.5 on 2026-09-11 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0009_remove_journalentry_write_off_amount_and_more"),
        ("settings", "0034_productionunit_expense_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="petty_cash_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The expense account used for mid-shift cash-outs (transport, ice, petty repairs).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.ledgeraccount",
                verbose_name="Petty cash expense account",
            ),
        ),
    ]
