# Generated by Django 6.0.5 on 2026-09-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_restaurant_petty_cash_expense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='require_payment_reference',
            field=models.BooleanField(default=False, help_text='When enabled, electronic (non-cash) payments must include a reference number at settlement.', verbose_name='Require payment reference'),
        ),
    ]
