# Generated by Django 6.0.5 on 2026-08-19 10:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PnLConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('business_day_start_hour', models.PositiveSmallIntegerField(default=0, help_text='Hour the business day starts (0 = midnight). Date D covers [D+hour, next D+hour).')),
                ('electricity_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='NGN per meter unit.', max_digits=14)),
                ('daily_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Flat daily amount. Not an asset schedule.', max_digits=14)),
                ('include_cash_variance', models.BooleanField(default=True, help_text='Pull shift-close short/excess onto the Daily P&L as an indirect line.')),
            ],
            options={
                'verbose_name': 'P&L configuration',
                'verbose_name_plural': 'P&L configuration',
            },
        ),
        migrations.CreateModel(
            name='PnLMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PnLRecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('DIRECT_DAILY', 'Direct — daily'), ('INDIRECT_DAILY', 'Indirect — daily'), ('INDIRECT_MONTHLY', 'Indirect — monthly'), ('INDIRECT_PERCENT', 'Indirect — % of gross sales'), ('EMPLOYEE_DAILY', 'Employee — daily'), ('EMPLOYEE_MONTHLY', 'Employee — monthly')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=7)),
                ('department', models.CharField(blank=True, choices=[('FOOD', 'Food'), ('DRINKS', 'Drinks')], max_length=10)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyPnL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_date', models.DateField()),
                ('period_start', models.DateTimeField(editable=False)),
                ('period_end', models.DateTimeField(editable=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('electricity_opening', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('electricity_closing', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('electricity_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=14)),
                ('employee_cost_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('gross_sales_food', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('gross_sales_drinks', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('net_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('cogs_drinks', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('kitchen_consumption', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('total_direct_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('total_employee_costs', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('depreciation', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('cash_variance', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('total_indirect_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('prime_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('gross_sales_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('round_off_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('net_sales_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('cogs_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('kitchen_consumption_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('total_direct_expenses_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('gross_profit_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('total_employee_costs_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('depreciation_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('cash_variance_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('total_indirect_expenses_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('prime_cost_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('net_profit_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='reports.dailypnl')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_daily_pnls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DailyPnLAdHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('section', models.CharField(choices=[('DIRECT', 'Direct'), ('INDIRECT', 'Indirect')], max_length=10)),
                ('department', models.CharField(blank=True, choices=[('FOOD', 'Food'), ('DRINKS', 'Drinks')], max_length=10)),
                ('pnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_rows', to='reports.dailypnl')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='DailyPnLCogsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=200)),
                ('department', models.CharField(default='DRINKS', max_length=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('kind', models.CharField(choices=[('SALE', 'Sale'), ('RETURN', 'Return'), ('WASTAGE', 'Wastage')], max_length=10)),
                ('pnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cogs_rows', to='reports.dailypnl')),
            ],
            options={
                'ordering': ['kind', 'item_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DailyPnLConsumptionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_rows', to='reports.dailypnl')),
            ],
            options={
                'ordering': ['item_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DailyPnLLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('GROSS_SALES', 'Gross sales'), ('ROUND_OFF', 'Round-off'), ('NET_SALES', 'Net sales'), ('COGS', 'COGS'), ('KITCHEN_CONSUMPTION', 'Kitchen consumption'), ('DIRECT', 'Direct'), ('GROSS_PROFIT', 'Gross profit'), ('PRIME_COST', 'Prime cost'), ('EMPLOYEE', 'Employee'), ('INDIRECT', 'Indirect'), ('DEPRECIATION', 'Depreciation'), ('CASH_VARIANCE', 'Cash variance'), ('NET_PROFIT', 'Net profit')], max_length=24)),
                ('label', models.CharField(max_length=100)),
                ('amount_food', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('amount_drinks', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('percent_of_gross', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7)),
                ('is_memo', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('COMPUTED', 'Computed'), ('SETTINGS', 'Settings'), ('METER', 'Meter'), ('MATERIAL', 'Material'), ('ADHOC', 'Ad-hoc'), ('VARIANCE', 'Variance')], default='COMPUTED', max_length=12)),
                ('pnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reports.dailypnl')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DailyPnLMaterialQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('pnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_qtys', to='reports.dailypnl')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pnl_quantities', to='reports.pnlmaterial')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailypnl',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('business_date',), name='reports_dailypnl_one_draft_per_date'),
        ),
        migrations.AddConstraint(
            model_name='dailypnl',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUBMITTED')), fields=('business_date',), name='reports_dailypnl_one_submitted_per_date'),
        ),
    ]
