# Generated by Django 6.0.5 on 2026-09-01 05:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnlconfiguration',
            name='business_day_start_hour',
            field=models.PositiveSmallIntegerField(default=0, help_text='The hour your business day starts (0 is midnight). For example, 6 means the day runs from 6am to 6am.'),
        ),
        migrations.AlterField(
            model_name='pnlconfiguration',
            name='daily_depreciation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='A fixed amount recorded each day for depreciation.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='pnlconfiguration',
            name='electricity_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Cost in naira for each unit of electricity.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='pnlconfiguration',
            name='include_cash_variance',
            field=models.BooleanField(default=True, help_text='When enabled, cash shortages or excesses at shift close appear on the Daily P&L.'),
        ),
    ]
