# Generated by Django 6.0.5 on 2026-09-09 05:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_pnlconfiguration_business_day_start_hour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypnlconsumptionrow',
            options={'ordering': ['kind', 'item_name', 'pk']},
        ),
        migrations.AddField(
            model_name='dailypnl',
            name='food_cost_variance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailypnl',
            name='food_cost_variance_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7),
        ),
        migrations.AddField(
            model_name='dailypnl',
            name='theoretical_food_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailypnl',
            name='theoretical_food_cost_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=7),
        ),
        migrations.AddField(
            model_name='dailypnlconsumptionrow',
            name='kind',
            field=models.CharField(choices=[('CONSUMPTION', 'Consumption'), ('WASTE', 'Waste')], default='CONSUMPTION', max_length=12),
        ),
        migrations.AlterField(
            model_name='dailypnlline',
            name='section',
            field=models.CharField(choices=[('GROSS_SALES', 'Gross sales'), ('ROUND_OFF', 'Round-off'), ('NET_SALES', 'Net sales'), ('COGS', 'COGS'), ('THEORETICAL_FOOD_COST', 'Theoretical food cost'), ('FOOD_COST_VARIANCE', 'Food cost variance'), ('KITCHEN_CONSUMPTION', 'Kitchen consumption'), ('DIRECT', 'Direct'), ('GROSS_PROFIT', 'Gross profit'), ('PRIME_COST', 'Prime cost'), ('EMPLOYEE', 'Employee'), ('INDIRECT', 'Indirect'), ('DEPRECIATION', 'Depreciation'), ('CASH_VARIANCE', 'Cash variance'), ('NET_PROFIT', 'Net profit')], max_length=24),
        ),
        migrations.CreateModel(
            name='DailyPnLTheoreticalRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient_name', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theoretical_rows', to='reports.dailypnl')),
            ],
            options={
                'ordering': ['ingredient_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DailyPnLUnmappedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unmapped_rows', to='reports.dailypnl')),
            ],
            options={
                'ordering': ['item_name', 'pk'],
            },
        ),
    ]
